---
- name: Install packages
  hosts: all
  tasks:
    - name: Install Apache package
      yum:
        name: httpd
        state: present

    - name: Install Time package
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - ntpd
        - chrony

    - name: Install DNS package
      yum:
        name: named
        state: present





