---
- name: Add or update user password
  hosts: all
  
  tasks:
  - name: Change “tommy” password
    user:
      name: tommy
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"