---
- name: Copy file from local to remote clients
  hosts: all
  
  tasks:
  - name: Copying file 
    become: true
    copy:
     src: /home/tommy/some.cfg
     dest: /tmp
     owner: tommy
     group: tommy
     mode: 0644